In [1]:
import numpy as np

data = np.array([1,2,3,4,5,6,7,8,9,10])

mask = data>1

mask

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [2]:
x=3

print( (x>4)*2 ) # if condition is not met, return 0

print( (x<4)*2 ) # if condition is met, return 1

(x==3)

0
2


True

# Indexes

In [3]:
array = np.array([5, 10, 3])
print(array)

print('index_max:', np.argmax(array))


[ 5 10  3]
index_max: 1


In [4]:
#matrix = np.arange(10).reshape(5, 2) + 10

matrix = np.array(
          [[ -2.90670824,   2.91098881], # 0, 1
          [ 10.22554588,  -8.44407272],  # 2, 3
          [  2.83001757,  -7.04704046],  # 4, 5
          [ -2.53250122,   4.0478344 ],  # 6, 7
          [-22.10226631,  12.45796204],  # 8, 9
          [-15.48008633,   9.76300812]]  # 10, 11
                                    )
 
print(matrix)

print('index_max:', np.argmax(matrix)) # max is 12.45796204


[[ -2.90670824   2.91098881]
 [ 10.22554588  -8.44407272]
 [  2.83001757  -7.04704046]
 [ -2.53250122   4.0478344 ]
 [-22.10226631  12.45796204]
 [-15.48008633   9.76300812]]
index_max: 9


In [5]:
print('coordinates:', np.where(matrix == 12.45796204))

coordinates: (array([4], dtype=int64), array([1], dtype=int64))


In [6]:
print('index_max_for_each_column:', np.argmax(matrix, axis=0)) # vertically

print('\n')

print('index_max_for_each_row:', np.argmax(matrix, axis=1)) # horizontally

index_max_for_each_column: [1 4]


index_max_for_each_row: [1 0 0 1 1 1]


# Create Pandas Dataframe 

In [7]:
# Pandas Dataframe
import pandas as pd

# initialize list of lists # BY ROW
data = [[1, 'species 1', 'genus 1'], 
        [2, 'species 2', 'genus 2'], 
        [3, 'x', 'genus 3'],
        [4, 'x', 'genus 4']] 
  
# Create the pandas DataFrame 
strains  = pd.DataFrame(data, columns=['strain_id', 'species', 'genus']) 
  
# print dataframe. 
strains  


strain_id    species    genus
0          1  species 1  genus 1
1          2  species 2  genus 2
2          3          x  genus 3
3          4          x  genus 4

## - Another option

In [8]:
# Pandas Dataframe
import pandas as pd

  
# Create the pandas DataFrame # BY COLUMN
strains  = pd.DataFrame(data = {'strain_id': [1, 2, 3, 4], 
                                'species': ['species 1', 'species 2', 'x', 'x'], 
                                'genus': ['genus 1', 'genus 2', 'genus 3', 'genus 4']},
                                ) 
  
# print dataframe. 
strains  

strain_id    species    genus
0          1  species 1  genus 1
1          2  species 2  genus 2
2          3          x  genus 3
3          4          x  genus 4

# Pandas DataFrame to SQLite

In [9]:
import sqlite3

# Create a database named test_database
conn = sqlite3.connect('SQL_database.db') 
c = conn.cursor()

# Create table inside the database
strains.to_sql('strainsSQL', conn, if_exists='replace', index = False)


# Print contents
c.execute('''  
SELECT * FROM strainsSQL
          ''')

for row in c.fetchall():
    print (row)


(1, 'species 1', 'genus 1')
(2, 'species 2', 'genus 2')
(3, 'x', 'genus 3')
(4, 'x', 'genus 4')


In [10]:
c.execute(''' 
    select strain_id from strainsSQL where species="x"
    ''')

# Print
for row in c.fetchall():
    print (row)

(3,)
(4,)


# SQLite to Pandas Dataframe

In [11]:
conn = sqlite3.connect('SQL_database.db')
strains = pd.read_sql('SELECT * FROM strainsSQL', conn)

print(strains)

strains[strains.species == "x"]['strain_id']

   strain_id    species    genus
0          1  species 1  genus 1
1          2  species 2  genus 2
2          3          x  genus 3
3          4          x  genus 4


2    3
3    4
Name: strain_id, dtype: int64